# Generated by Django 2.2.5 on 2019-10-19 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('descripcion', models.CharField(max_length=100, unique=True, verbose_name='Descripcion')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='clients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('first_name', models.CharField(max_length=100, verbose_name='First name ')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last name ')),
                ('email', models.EmailField(max_length=50, verbose_name='E-mail')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='clients/', verbose_name='Author image')),
                ('phone', models.CharField(max_length=11, verbose_name='Phone')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('credit_card_number', models.CharField(max_length=50, verbose_name='Credit_card_number')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Title')),
                ('addreviatons', models.CharField(max_length=100, verbose_name='Addreviatons')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='gender',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Title')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Gender',
                'verbose_name_plural': 'Genders',
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Title')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='clients/', verbose_name='Author image')),
                ('quality', models.CharField(max_length=100, verbose_name='Quality')),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.categories')),
                ('id_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.clients')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.AddField(
            model_name='clients',
            name='id_cuntry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.country'),
        ),
        migrations.AddField(
            model_name='clients',
            name='id_gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.gender'),
        ),
    ]
