# Generated by Django 2.2.5 on 2019-10-19 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_auto_20191019_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping',
            name='shopping_date',
            field=models.DateField(auto_now_add=True, verbose_name='Shopping_date'),
        ),
    ]
