# Generated by Django 2.2.5 on 2019-10-19 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_auto_20191019_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='id_client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.clients'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopping',
            name='id_products',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.product'),
            preserve_default=False,
        ),
    ]
